print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
print("Conta Github criada!")
print("Github Desktop instalado!")
print("Repositorio Clonado!")